### ISSUE TITLE
Drag the avatar around

### ISSUE THREAD

**Issue by Njima1572** [Amijakan/spatialchatclone#14]
Resources that might be useful
---
- https://blog.mksc.jp/contents/drag-on-react

### Sender
1. Add the position data (x, y) via RTCDataChannel to each peer connection
2. Stream the position data

### Receiver
1. Update the position of the circle according to the data received

**Comment by Njima1572** [comment]
This data can be sent through RTCSender right?

**Comment by Njima1572** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel

**Comment by siberowl** [comment]
Yeah RTCDataChannel seems like the right thing to use.
