### ISSUE TITLE
Be able to chat with other people via audio

### ISSUE THREAD

**Issue by Njima1572** [Amijakan/spatialchatclone#15]
- [x] #26 
- [x] #28
- [x] #44

**Comment by Njima1572** [comment]
Some libraries that could be used
---
- https://github.com/alemangui/pizzicato

**Comment by siberowl** [comment]
Note to self regarding WebRTC:
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Connectivity
https://medium.com/swlh/manage-dynamic-multi-peer-connections-in-webrtc-3ff4e10f75b7
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createOffer

**Comment by siberowl** [comment]
Complete #26 first
