### ISSUE TITLE
Combine join and chat pages into one url

### ISSUE THREAD

**Issue by siberowl** [Amijakan/spatialchatclone#29]
Instead of jumping between url's, organize the components onto a single page.

**Comment by Njima1572** [comment]
Also make it into separate rooms by `/:room_id` routing

**Comment by Njima1572** [comment]
server has rooms like
```
User = {id: string}
Room = {id: string, members: User[] };
rooms = {
   [room_id]: Room
}
```

Client access room with `/:room_id`
