### ISSUE TITLE
Change Volume of each peer

### ISSUE THREAD

**Issue by Njima1572** [Amijakan/spatialchatclone#41]
Change volume part reference
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings

## Things to do (Example)
1. Make a list of people in the same room (of their MediaStream)
2. Make a slide bar for each user to adjust volume

**Comment by Njima1572** [comment]
Will later advance to change volume according to distance

**Comment by siberowl** [comment]
I think I can just change the MediaElement volume.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume
